before_script:
    - ln -sv ${CI_PROJECT_DIR} ${CI_PROJECT_DIR}/src
    - export GOPATH=$GOPATH:${CI_PROJECT_DIR}

stages:
- build
- test
- deploy

build_sharkstore:
  stage: build
  script:
  - echo "build sharkstore data-server....."

  - mkdir -p ${CI_PROJECT_DIR}/data-server/build/
  - cd ${CI_PROJECT_DIR}/data-server/build/ &&
    cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TEST=ON -DBUILD_TOOL=ON &&
    make -j 4

  - echo "build sharkstore master-server"
  - cd ${CI_PROJECT_DIR}/master-server/cmd && go build -o master-server

  - echo "build sharkstore gateway-server"
  - cd ${CI_PROJECT_DIR}/proxy/gateway-server/cmd && go build -o gateway-server

  - echo "done"

test_sharkstore_ds:
  stage: test
  script:
  - echo "run sharkstore test....."

  - cd ${CI_PROJECT_DIR}/data-server/build/test
  - echo $PWD
  - ./range_ddl_unittest
  - ./range_meta_unittest
  - ./range_raw_unittest
  - ./range_sql_unittest
  - ./store_unittest

  - echo "done"

test_sharkstore_gs:
  stage: test
  script:
  - echo "run sharkstore test....."

  - cd ${CI_PROJECT_DIR}/proxy/gateway-server/
  - go test -v -short $(go list ./...)

  - echo "done"

deploy_sharkstore:
  stage: deploy
  script:
  - echo "todo deploy"

