stages:
- build
- test
- deploy

build_sharkstore:
  stage: build
  script:
  - echo "build sharkstore....."
  - echo "mvn clean"
  - echo "done"

test_sharkstore:
  stage: test
  script:
  - echo "run sharkstore test....."
  - echo "java -test"
  - echo "done"

deploy_sharkstore:
  stage: deploy
  script:
  - echo "deploy sharkstore...."
  - echo "run mvn install"
  - echo "done"


