before_script:
    - ln -sv ${CI_PROJECT_DIR} ${CI_PROJECT_DIR}/src
    - export GOPATH=$GOPATH:${CI_PROJECT_DIR}

stages:
- test
- deploy

ds_ci:
  stage: test
  script:
  - echo "build sharkstore data-server....."
  - mkdir -p ${CI_PROJECT_DIR}/data-server/build/
  - cd ${CI_PROJECT_DIR}/data-server/build/ &&
    cmake .. -DBUILD_TEST=ON && make -j `nproc`

  - echo "run data-server test....."
  - cd ${CI_PROJECT_DIR}/data-server/build && ctest

gw_ci:
  stage: test
  script:
  - echo "build sharkstore gateway-server"
  - cd ${CI_PROJECT_DIR}/proxy/gateway-server/cmd && go build -o gateway-server

  - echo "run gateway-server test....."
  - cd ${CI_PROJECT_DIR}/proxy/gateway-server/
  - go test $(go list ./...)

ms_ci:
  stage: test
  script:
  - echo "build sharkstore master-server"
  - cd ${CI_PROJECT_DIR}/master-server/cmd && go build -o master-server

deploy:
  stage: deploy
  script:
  - echo "todo deploy..."

