max-record-limit = 10000
aggr-func = true

[performance]
#proxy concurrency number
max-work-num = 100
#task queue size
max-task-queue-len = 10000
#keep connect size for each ds
grpc-pool-size = 10
# 128 KB
grpc-win-size = 131072
#be identified to 'slow command' when time consuming is greater than the value, unit: millisecond
slow-insert = "200ms"
slow-select = "500ms"
slow-delete = "200ms"


[cluster]
id = 999
address = ["172.22.212.59:7791","172.22.212.60:7791","172.22.212.61:7791"]
token = "test"


[log]
dir = "/export/Logs/shark-bench999"
module = "bench"
# log level debug, info, warn, error
level = "info"

[benchmark]
type = 1
data-len = 256
send-num = 100
threads = 10
db = "test"
table = "testh"
batch = 10
#1-16384
#scope = 1
