// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: raft.proto
#ifndef GRPC_raft_2eproto__INCLUDED
#define GRPC_raft_2eproto__INCLUDED

#include "raft.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace fbase {
namespace raft {
namespace impl {
namespace pb {

class MultiRaft final {
 public:
  static constexpr char const* service_full_name() {
    return "fbase.raft.impl.pb.MultiRaft";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RaftMessage(::grpc::ClientContext* context, const ::fbase::raft::impl::pb::RaftMessageRequest& request, ::fbase::raft::impl::pb::RaftMessageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fbase::raft::impl::pb::RaftMessageResponse>> AsyncRaftMessage(::grpc::ClientContext* context, const ::fbase::raft::impl::pb::RaftMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fbase::raft::impl::pb::RaftMessageResponse>>(AsyncRaftMessageRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fbase::raft::impl::pb::RaftMessageResponse>* AsyncRaftMessageRaw(::grpc::ClientContext* context, const ::fbase::raft::impl::pb::RaftMessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RaftMessage(::grpc::ClientContext* context, const ::fbase::raft::impl::pb::RaftMessageRequest& request, ::fbase::raft::impl::pb::RaftMessageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fbase::raft::impl::pb::RaftMessageResponse>> AsyncRaftMessage(::grpc::ClientContext* context, const ::fbase::raft::impl::pb::RaftMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fbase::raft::impl::pb::RaftMessageResponse>>(AsyncRaftMessageRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::fbase::raft::impl::pb::RaftMessageResponse>* AsyncRaftMessageRaw(::grpc::ClientContext* context, const ::fbase::raft::impl::pb::RaftMessageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_RaftMessage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RaftMessage(::grpc::ServerContext* context, const ::fbase::raft::impl::pb::RaftMessageRequest* request, ::fbase::raft::impl::pb::RaftMessageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RaftMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RaftMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RaftMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RaftMessage(::grpc::ServerContext* context, const ::fbase::raft::impl::pb::RaftMessageRequest* request, ::fbase::raft::impl::pb::RaftMessageResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRaftMessage(::grpc::ServerContext* context, ::fbase::raft::impl::pb::RaftMessageRequest* request, ::grpc::ServerAsyncResponseWriter< ::fbase::raft::impl::pb::RaftMessageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RaftMessage<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_RaftMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RaftMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RaftMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RaftMessage(::grpc::ServerContext* context, const ::fbase::raft::impl::pb::RaftMessageRequest* request, ::fbase::raft::impl::pb::RaftMessageResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RaftMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RaftMessage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::fbase::raft::impl::pb::RaftMessageRequest, ::fbase::raft::impl::pb::RaftMessageResponse>(std::bind(&WithStreamedUnaryMethod_RaftMessage<BaseClass>::StreamedRaftMessage, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RaftMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RaftMessage(::grpc::ServerContext* context, const ::fbase::raft::impl::pb::RaftMessageRequest* request, ::fbase::raft::impl::pb::RaftMessageResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRaftMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fbase::raft::impl::pb::RaftMessageRequest,::fbase::raft::impl::pb::RaftMessageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RaftMessage<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RaftMessage<Service > StreamedService;
};

}  // namespace pb
}  // namespace impl
}  // namespace raft
}  // namespace fbase


#endif  // GRPC_raft_2eproto__INCLUDED
