// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: alarmpb.proto

/*
	Package alarmpb is a generated protocol buffer package.

	It is generated from these files:
		alarmpb.proto

	It has these top-level messages:
		RequestHeader
		ResponseHeader
		SimpleAlarmRequest
		SimpleAlarmResponse
		TaskAlarmRequest
		TaskTimeout
		TaskLongTimeRunning
		TaskAlarmResponse
		NodeRangeAlarmRequest
		RangeNoHeartbeatAlarm
		NodeNoHeartbeatAlarm
		NodeDiskSizeAlarm
		NodeLeaderCountAlarm
		NodeRangeAlarmResponse
		AliveRequest
		AliveResponse
		SimpleRequest
		SimpleResponse
*/
package alarmpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import taskpb "model/pkg/taskpb"
import metapb "model/pkg/metapb"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskAlarmType int32

const (
	TaskAlarmType_TIMEOUT           TaskAlarmType = 0
	TaskAlarmType_LONG_TIME_RUNNING TaskAlarmType = 1
)

var TaskAlarmType_name = map[int32]string{
	0: "TIMEOUT",
	1: "LONG_TIME_RUNNING",
}
var TaskAlarmType_value = map[string]int32{
	"TIMEOUT":           0,
	"LONG_TIME_RUNNING": 1,
}

func (x TaskAlarmType) String() string {
	return proto.EnumName(TaskAlarmType_name, int32(x))
}
func (TaskAlarmType) EnumDescriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{0} }

type NodeRangeAlarmType int32

const (
	NodeRangeAlarmType_RANGE_NO_HEARTBEAT NodeRangeAlarmType = 0
	NodeRangeAlarmType_NODE_NO_HEARTBEAT  NodeRangeAlarmType = 1
	NodeRangeAlarmType_NODE_DISK_SIZE     NodeRangeAlarmType = 2
	NodeRangeAlarmType_NODE_LEADER_COUNT  NodeRangeAlarmType = 3
)

var NodeRangeAlarmType_name = map[int32]string{
	0: "RANGE_NO_HEARTBEAT",
	1: "NODE_NO_HEARTBEAT",
	2: "NODE_DISK_SIZE",
	3: "NODE_LEADER_COUNT",
}
var NodeRangeAlarmType_value = map[string]int32{
	"RANGE_NO_HEARTBEAT": 0,
	"NODE_NO_HEARTBEAT":  1,
	"NODE_DISK_SIZE":     2,
	"NODE_LEADER_COUNT":  3,
}

func (x NodeRangeAlarmType) String() string {
	return proto.EnumName(NodeRangeAlarmType_name, int32(x))
}
func (NodeRangeAlarmType) EnumDescriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{1} }

type RequestHeader struct {
	ClusterId int64 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
}

func (m *RequestHeader) Reset()                    { *m = RequestHeader{} }
func (m *RequestHeader) String() string            { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()               {}
func (*RequestHeader) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{0} }

func (m *RequestHeader) GetClusterId() int64 {
	if m != nil {
		return m.ClusterId
	}
	return 0
}

type ResponseHeader struct {
	Code  int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *ResponseHeader) Reset()                    { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string            { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()               {}
func (*ResponseHeader) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{1} }

func (m *ResponseHeader) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseHeader) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SimpleAlarmRequest struct {
	Head     *RequestHeader `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
	Describe string         `protobuf:"bytes,2,opt,name=Describe,proto3" json:"Describe,omitempty"`
}

func (m *SimpleAlarmRequest) Reset()                    { *m = SimpleAlarmRequest{} }
func (m *SimpleAlarmRequest) String() string            { return proto.CompactTextString(m) }
func (*SimpleAlarmRequest) ProtoMessage()               {}
func (*SimpleAlarmRequest) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{2} }

func (m *SimpleAlarmRequest) GetHead() *RequestHeader {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *SimpleAlarmRequest) GetDescribe() string {
	if m != nil {
		return m.Describe
	}
	return ""
}

type SimpleAlarmResponse struct {
	Head *ResponseHeader `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
}

func (m *SimpleAlarmResponse) Reset()                    { *m = SimpleAlarmResponse{} }
func (m *SimpleAlarmResponse) String() string            { return proto.CompactTextString(m) }
func (*SimpleAlarmResponse) ProtoMessage()               {}
func (*SimpleAlarmResponse) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{3} }

func (m *SimpleAlarmResponse) GetHead() *ResponseHeader {
	if m != nil {
		return m.Head
	}
	return nil
}

type TaskAlarmRequest struct {
	Head                     *RequestHeader       `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
	Type                     TaskAlarmType        `protobuf:"varint,2,opt,name=type,proto3,enum=alarmpb.TaskAlarmType" json:"type,omitempty"`
	Task                     *taskpb.Task         `protobuf:"bytes,3,opt,name=task" json:"task,omitempty"`
	TaskTimeoutAlarm         *TaskTimeout         `protobuf:"bytes,4,opt,name=task_timeout_alarm,json=taskTimeoutAlarm" json:"task_timeout_alarm,omitempty"`
	TaskLongTimeRunningAlarm *TaskLongTimeRunning `protobuf:"bytes,5,opt,name=task_long_time_running_alarm,json=taskLongTimeRunningAlarm" json:"task_long_time_running_alarm,omitempty"`
	Describe                 string               `protobuf:"bytes,6,opt,name=Describe,proto3" json:"Describe,omitempty"`
	SampleJson               []string             `protobuf:"bytes,10,rep,name=sample_json,json=sampleJson" json:"sample_json,omitempty"`
}

func (m *TaskAlarmRequest) Reset()                    { *m = TaskAlarmRequest{} }
func (m *TaskAlarmRequest) String() string            { return proto.CompactTextString(m) }
func (*TaskAlarmRequest) ProtoMessage()               {}
func (*TaskAlarmRequest) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{4} }

func (m *TaskAlarmRequest) GetHead() *RequestHeader {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *TaskAlarmRequest) GetType() TaskAlarmType {
	if m != nil {
		return m.Type
	}
	return TaskAlarmType_TIMEOUT
}

func (m *TaskAlarmRequest) GetTask() *taskpb.Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *TaskAlarmRequest) GetTaskTimeoutAlarm() *TaskTimeout {
	if m != nil {
		return m.TaskTimeoutAlarm
	}
	return nil
}

func (m *TaskAlarmRequest) GetTaskLongTimeRunningAlarm() *TaskLongTimeRunning {
	if m != nil {
		return m.TaskLongTimeRunningAlarm
	}
	return nil
}

func (m *TaskAlarmRequest) GetDescribe() string {
	if m != nil {
		return m.Describe
	}
	return ""
}

func (m *TaskAlarmRequest) GetSampleJson() []string {
	if m != nil {
		return m.SampleJson
	}
	return nil
}

type TaskTimeout struct {
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Takes int64  `protobuf:"varint,3,opt,name=takes,proto3" json:"takes,omitempty"`
}

func (m *TaskTimeout) Reset()                    { *m = TaskTimeout{} }
func (m *TaskTimeout) String() string            { return proto.CompactTextString(m) }
func (*TaskTimeout) ProtoMessage()               {}
func (*TaskTimeout) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{5} }

func (m *TaskTimeout) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *TaskTimeout) GetTakes() int64 {
	if m != nil {
		return m.Takes
	}
	return 0
}

type TaskLongTimeRunning struct {
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Takes int64  `protobuf:"varint,3,opt,name=takes,proto3" json:"takes,omitempty"`
}

func (m *TaskLongTimeRunning) Reset()                    { *m = TaskLongTimeRunning{} }
func (m *TaskLongTimeRunning) String() string            { return proto.CompactTextString(m) }
func (*TaskLongTimeRunning) ProtoMessage()               {}
func (*TaskLongTimeRunning) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{6} }

func (m *TaskLongTimeRunning) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *TaskLongTimeRunning) GetTakes() int64 {
	if m != nil {
		return m.Takes
	}
	return 0
}

type TaskAlarmResponse struct {
	Head *ResponseHeader `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
}

func (m *TaskAlarmResponse) Reset()                    { *m = TaskAlarmResponse{} }
func (m *TaskAlarmResponse) String() string            { return proto.CompactTextString(m) }
func (*TaskAlarmResponse) ProtoMessage()               {}
func (*TaskAlarmResponse) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{7} }

func (m *TaskAlarmResponse) GetHead() *ResponseHeader {
	if m != nil {
		return m.Head
	}
	return nil
}

type NodeRangeAlarmRequest struct {
	Head                 *RequestHeader         `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
	Type                 NodeRangeAlarmType     `protobuf:"varint,2,opt,name=type,proto3,enum=alarmpb.NodeRangeAlarmType" json:"type,omitempty"`
	RangeNoHbAlarm       *RangeNoHeartbeatAlarm `protobuf:"bytes,3,opt,name=range_no_hb_alarm,json=rangeNoHbAlarm" json:"range_no_hb_alarm,omitempty"`
	NodeNoHbAlarm        *NodeNoHeartbeatAlarm  `protobuf:"bytes,4,opt,name=node_no_hb_alarm,json=nodeNoHbAlarm" json:"node_no_hb_alarm,omitempty"`
	NodeDiskSizeAlarm    *NodeDiskSizeAlarm     `protobuf:"bytes,5,opt,name=node_disk_size_alarm,json=nodeDiskSizeAlarm" json:"node_disk_size_alarm,omitempty"`
	NodeLeaderCountAlarm *NodeLeaderCountAlarm  `protobuf:"bytes,6,opt,name=node_leader_count_alarm,json=nodeLeaderCountAlarm" json:"node_leader_count_alarm,omitempty"`
	Describe             string                 `protobuf:"bytes,7,opt,name=Describe,proto3" json:"Describe,omitempty"`
	SampleJson           []string               `protobuf:"bytes,10,rep,name=sample_json,json=sampleJson" json:"sample_json,omitempty"`
}

func (m *NodeRangeAlarmRequest) Reset()                    { *m = NodeRangeAlarmRequest{} }
func (m *NodeRangeAlarmRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeRangeAlarmRequest) ProtoMessage()               {}
func (*NodeRangeAlarmRequest) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{8} }

func (m *NodeRangeAlarmRequest) GetHead() *RequestHeader {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *NodeRangeAlarmRequest) GetType() NodeRangeAlarmType {
	if m != nil {
		return m.Type
	}
	return NodeRangeAlarmType_RANGE_NO_HEARTBEAT
}

func (m *NodeRangeAlarmRequest) GetRangeNoHbAlarm() *RangeNoHeartbeatAlarm {
	if m != nil {
		return m.RangeNoHbAlarm
	}
	return nil
}

func (m *NodeRangeAlarmRequest) GetNodeNoHbAlarm() *NodeNoHeartbeatAlarm {
	if m != nil {
		return m.NodeNoHbAlarm
	}
	return nil
}

func (m *NodeRangeAlarmRequest) GetNodeDiskSizeAlarm() *NodeDiskSizeAlarm {
	if m != nil {
		return m.NodeDiskSizeAlarm
	}
	return nil
}

func (m *NodeRangeAlarmRequest) GetNodeLeaderCountAlarm() *NodeLeaderCountAlarm {
	if m != nil {
		return m.NodeLeaderCountAlarm
	}
	return nil
}

func (m *NodeRangeAlarmRequest) GetDescribe() string {
	if m != nil {
		return m.Describe
	}
	return ""
}

func (m *NodeRangeAlarmRequest) GetSampleJson() []string {
	if m != nil {
		return m.SampleJson
	}
	return nil
}

type RangeNoHeartbeatAlarm struct {
	Range             *metapb.Range `protobuf:"bytes,1,opt,name=range" json:"range,omitempty"`
	LastHeartbeatTime string        `protobuf:"bytes,2,opt,name=last_heartbeat_time,json=lastHeartbeatTime,proto3" json:"last_heartbeat_time,omitempty"`
}

func (m *RangeNoHeartbeatAlarm) Reset()                    { *m = RangeNoHeartbeatAlarm{} }
func (m *RangeNoHeartbeatAlarm) String() string            { return proto.CompactTextString(m) }
func (*RangeNoHeartbeatAlarm) ProtoMessage()               {}
func (*RangeNoHeartbeatAlarm) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{9} }

func (m *RangeNoHeartbeatAlarm) GetRange() *metapb.Range {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *RangeNoHeartbeatAlarm) GetLastHeartbeatTime() string {
	if m != nil {
		return m.LastHeartbeatTime
	}
	return ""
}

type NodeNoHeartbeatAlarm struct {
	Node              *metapb.Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	LastHeartbeatTime string       `protobuf:"bytes,2,opt,name=last_heartbeat_time,json=lastHeartbeatTime,proto3" json:"last_heartbeat_time,omitempty"`
}

func (m *NodeNoHeartbeatAlarm) Reset()                    { *m = NodeNoHeartbeatAlarm{} }
func (m *NodeNoHeartbeatAlarm) String() string            { return proto.CompactTextString(m) }
func (*NodeNoHeartbeatAlarm) ProtoMessage()               {}
func (*NodeNoHeartbeatAlarm) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{10} }

func (m *NodeNoHeartbeatAlarm) GetNode() *metapb.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeNoHeartbeatAlarm) GetLastHeartbeatTime() string {
	if m != nil {
		return m.LastHeartbeatTime
	}
	return ""
}

type NodeDiskSizeAlarm struct {
	Node     *metapb.Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	DiskSize int64        `protobuf:"varint,2,opt,name=disk_size,json=diskSize,proto3" json:"disk_size,omitempty"`
}

func (m *NodeDiskSizeAlarm) Reset()                    { *m = NodeDiskSizeAlarm{} }
func (m *NodeDiskSizeAlarm) String() string            { return proto.CompactTextString(m) }
func (*NodeDiskSizeAlarm) ProtoMessage()               {}
func (*NodeDiskSizeAlarm) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{11} }

func (m *NodeDiskSizeAlarm) GetNode() *metapb.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeDiskSizeAlarm) GetDiskSize() int64 {
	if m != nil {
		return m.DiskSize
	}
	return 0
}

type NodeLeaderCountAlarm struct {
	Node        *metapb.Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	LeaderCount int64        `protobuf:"varint,2,opt,name=leader_count,json=leaderCount,proto3" json:"leader_count,omitempty"`
}

func (m *NodeLeaderCountAlarm) Reset()                    { *m = NodeLeaderCountAlarm{} }
func (m *NodeLeaderCountAlarm) String() string            { return proto.CompactTextString(m) }
func (*NodeLeaderCountAlarm) ProtoMessage()               {}
func (*NodeLeaderCountAlarm) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{12} }

func (m *NodeLeaderCountAlarm) GetNode() *metapb.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeLeaderCountAlarm) GetLeaderCount() int64 {
	if m != nil {
		return m.LeaderCount
	}
	return 0
}

type NodeRangeAlarmResponse struct {
	Head *ResponseHeader `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
}

func (m *NodeRangeAlarmResponse) Reset()                    { *m = NodeRangeAlarmResponse{} }
func (m *NodeRangeAlarmResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeRangeAlarmResponse) ProtoMessage()               {}
func (*NodeRangeAlarmResponse) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{13} }

func (m *NodeRangeAlarmResponse) GetHead() *ResponseHeader {
	if m != nil {
		return m.Head
	}
	return nil
}

type AliveRequest struct {
	Head       *RequestHeader `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
	SampleJson []string       `protobuf:"bytes,10,rep,name=sample_json,json=sampleJson" json:"sample_json,omitempty"`
}

func (m *AliveRequest) Reset()                    { *m = AliveRequest{} }
func (m *AliveRequest) String() string            { return proto.CompactTextString(m) }
func (*AliveRequest) ProtoMessage()               {}
func (*AliveRequest) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{14} }

func (m *AliveRequest) GetHead() *RequestHeader {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *AliveRequest) GetSampleJson() []string {
	if m != nil {
		return m.SampleJson
	}
	return nil
}

type AliveResponse struct {
	Head *ResponseHeader `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
}

func (m *AliveResponse) Reset()                    { *m = AliveResponse{} }
func (m *AliveResponse) String() string            { return proto.CompactTextString(m) }
func (*AliveResponse) ProtoMessage()               {}
func (*AliveResponse) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{15} }

func (m *AliveResponse) GetHead() *ResponseHeader {
	if m != nil {
		return m.Head
	}
	return nil
}

type SimpleRequest struct {
	Head       *RequestHeader `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
	Title      string         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content    string         `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SampleJson []string       `protobuf:"bytes,10,rep,name=sample_json,json=sampleJson" json:"sample_json,omitempty"`
}

func (m *SimpleRequest) Reset()                    { *m = SimpleRequest{} }
func (m *SimpleRequest) String() string            { return proto.CompactTextString(m) }
func (*SimpleRequest) ProtoMessage()               {}
func (*SimpleRequest) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{16} }

func (m *SimpleRequest) GetHead() *RequestHeader {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *SimpleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SimpleRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SimpleRequest) GetSampleJson() []string {
	if m != nil {
		return m.SampleJson
	}
	return nil
}

type SimpleResponse struct {
	Head *ResponseHeader `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
}

func (m *SimpleResponse) Reset()                    { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string            { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()               {}
func (*SimpleResponse) Descriptor() ([]byte, []int) { return fileDescriptorAlarmpb, []int{17} }

func (m *SimpleResponse) GetHead() *ResponseHeader {
	if m != nil {
		return m.Head
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "alarmpb.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "alarmpb.ResponseHeader")
	proto.RegisterType((*SimpleAlarmRequest)(nil), "alarmpb.SimpleAlarmRequest")
	proto.RegisterType((*SimpleAlarmResponse)(nil), "alarmpb.SimpleAlarmResponse")
	proto.RegisterType((*TaskAlarmRequest)(nil), "alarmpb.TaskAlarmRequest")
	proto.RegisterType((*TaskTimeout)(nil), "alarmpb.TaskTimeout")
	proto.RegisterType((*TaskLongTimeRunning)(nil), "alarmpb.TaskLongTimeRunning")
	proto.RegisterType((*TaskAlarmResponse)(nil), "alarmpb.TaskAlarmResponse")
	proto.RegisterType((*NodeRangeAlarmRequest)(nil), "alarmpb.NodeRangeAlarmRequest")
	proto.RegisterType((*RangeNoHeartbeatAlarm)(nil), "alarmpb.RangeNoHeartbeatAlarm")
	proto.RegisterType((*NodeNoHeartbeatAlarm)(nil), "alarmpb.NodeNoHeartbeatAlarm")
	proto.RegisterType((*NodeDiskSizeAlarm)(nil), "alarmpb.NodeDiskSizeAlarm")
	proto.RegisterType((*NodeLeaderCountAlarm)(nil), "alarmpb.NodeLeaderCountAlarm")
	proto.RegisterType((*NodeRangeAlarmResponse)(nil), "alarmpb.NodeRangeAlarmResponse")
	proto.RegisterType((*AliveRequest)(nil), "alarmpb.AliveRequest")
	proto.RegisterType((*AliveResponse)(nil), "alarmpb.AliveResponse")
	proto.RegisterType((*SimpleRequest)(nil), "alarmpb.SimpleRequest")
	proto.RegisterType((*SimpleResponse)(nil), "alarmpb.SimpleResponse")
	proto.RegisterEnum("alarmpb.TaskAlarmType", TaskAlarmType_name, TaskAlarmType_value)
	proto.RegisterEnum("alarmpb.NodeRangeAlarmType", NodeRangeAlarmType_name, NodeRangeAlarmType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Alarm service

type AlarmClient interface {
	//    rpc TaskAlarm(TaskAlarmRequest) returns (TaskAlarmResponse) {}
	NodeRangeAlarm(ctx context.Context, in *NodeRangeAlarmRequest, opts ...grpc.CallOption) (*NodeRangeAlarmResponse, error)
	//    rpc AliveAlarm(AliveRequest) returns (AliveResponse) {}
	SimpleAlarm(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type alarmClient struct {
	cc *grpc.ClientConn
}

func NewAlarmClient(cc *grpc.ClientConn) AlarmClient {
	return &alarmClient{cc}
}

func (c *alarmClient) NodeRangeAlarm(ctx context.Context, in *NodeRangeAlarmRequest, opts ...grpc.CallOption) (*NodeRangeAlarmResponse, error) {
	out := new(NodeRangeAlarmResponse)
	err := grpc.Invoke(ctx, "/alarmpb.Alarm/NodeRangeAlarm", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) SimpleAlarm(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := grpc.Invoke(ctx, "/alarmpb.Alarm/SimpleAlarm", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Alarm service

type AlarmServer interface {
	//    rpc TaskAlarm(TaskAlarmRequest) returns (TaskAlarmResponse) {}
	NodeRangeAlarm(context.Context, *NodeRangeAlarmRequest) (*NodeRangeAlarmResponse, error)
	//    rpc AliveAlarm(AliveRequest) returns (AliveResponse) {}
	SimpleAlarm(context.Context, *SimpleRequest) (*SimpleResponse, error)
}

func RegisterAlarmServer(s *grpc.Server, srv AlarmServer) {
	s.RegisterService(&_Alarm_serviceDesc, srv)
}

func _Alarm_NodeRangeAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRangeAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).NodeRangeAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/NodeRangeAlarm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).NodeRangeAlarm(ctx, req.(*NodeRangeAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_SimpleAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).SimpleAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/SimpleAlarm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).SimpleAlarm(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Alarm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alarmpb.Alarm",
	HandlerType: (*AlarmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeRangeAlarm",
			Handler:    _Alarm_NodeRangeAlarm_Handler,
		},
		{
			MethodName: "SimpleAlarm",
			Handler:    _Alarm_SimpleAlarm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alarmpb.proto",
}

func (m *RequestHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestHeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ClusterId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.ClusterId))
	}
	return i, nil
}

func (m *ResponseHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseHeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Code))
	}
	if len(m.Error) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(len(m.Error)))
		i += copy(dAtA[i:], m.Error)
	}
	return i, nil
}

func (m *SimpleAlarmRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimpleAlarmRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Head != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Head.Size()))
		n1, err := m.Head.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Describe) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(len(m.Describe)))
		i += copy(dAtA[i:], m.Describe)
	}
	return i, nil
}

func (m *SimpleAlarmResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimpleAlarmResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Head != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Head.Size()))
		n2, err := m.Head.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func (m *TaskAlarmRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskAlarmRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Head != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Head.Size()))
		n3, err := m.Head.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.Type != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Type))
	}
	if m.Task != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Task.Size()))
		n4, err := m.Task.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.TaskTimeoutAlarm != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.TaskTimeoutAlarm.Size()))
		n5, err := m.TaskTimeoutAlarm.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.TaskLongTimeRunningAlarm != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.TaskLongTimeRunningAlarm.Size()))
		n6, err := m.TaskLongTimeRunningAlarm.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if len(m.Describe) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(len(m.Describe)))
		i += copy(dAtA[i:], m.Describe)
	}
	if len(m.SampleJson) > 0 {
		for _, s := range m.SampleJson {
			dAtA[i] = 0x52
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *TaskTimeout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskTimeout) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Start) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(len(m.Start)))
		i += copy(dAtA[i:], m.Start)
	}
	if m.Takes != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Takes))
	}
	return i, nil
}

func (m *TaskLongTimeRunning) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskLongTimeRunning) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Start) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(len(m.Start)))
		i += copy(dAtA[i:], m.Start)
	}
	if m.Takes != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Takes))
	}
	return i, nil
}

func (m *TaskAlarmResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskAlarmResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Head != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Head.Size()))
		n7, err := m.Head.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}

func (m *NodeRangeAlarmRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeRangeAlarmRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Head != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Head.Size()))
		n8, err := m.Head.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	if m.Type != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Type))
	}
	if m.RangeNoHbAlarm != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.RangeNoHbAlarm.Size()))
		n9, err := m.RangeNoHbAlarm.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	if m.NodeNoHbAlarm != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.NodeNoHbAlarm.Size()))
		n10, err := m.NodeNoHbAlarm.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	if m.NodeDiskSizeAlarm != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.NodeDiskSizeAlarm.Size()))
		n11, err := m.NodeDiskSizeAlarm.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	if m.NodeLeaderCountAlarm != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.NodeLeaderCountAlarm.Size()))
		n12, err := m.NodeLeaderCountAlarm.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n12
	}
	if len(m.Describe) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(len(m.Describe)))
		i += copy(dAtA[i:], m.Describe)
	}
	if len(m.SampleJson) > 0 {
		for _, s := range m.SampleJson {
			dAtA[i] = 0x52
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *RangeNoHeartbeatAlarm) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RangeNoHeartbeatAlarm) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Range != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Range.Size()))
		n13, err := m.Range.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n13
	}
	if len(m.LastHeartbeatTime) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(len(m.LastHeartbeatTime)))
		i += copy(dAtA[i:], m.LastHeartbeatTime)
	}
	return i, nil
}

func (m *NodeNoHeartbeatAlarm) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeNoHeartbeatAlarm) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Node != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Node.Size()))
		n14, err := m.Node.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n14
	}
	if len(m.LastHeartbeatTime) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(len(m.LastHeartbeatTime)))
		i += copy(dAtA[i:], m.LastHeartbeatTime)
	}
	return i, nil
}

func (m *NodeDiskSizeAlarm) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeDiskSizeAlarm) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Node != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Node.Size()))
		n15, err := m.Node.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n15
	}
	if m.DiskSize != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.DiskSize))
	}
	return i, nil
}

func (m *NodeLeaderCountAlarm) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeLeaderCountAlarm) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Node != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Node.Size()))
		n16, err := m.Node.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n16
	}
	if m.LeaderCount != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.LeaderCount))
	}
	return i, nil
}

func (m *NodeRangeAlarmResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeRangeAlarmResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Head != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Head.Size()))
		n17, err := m.Head.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n17
	}
	return i, nil
}

func (m *AliveRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AliveRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Head != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Head.Size()))
		n18, err := m.Head.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n18
	}
	if len(m.SampleJson) > 0 {
		for _, s := range m.SampleJson {
			dAtA[i] = 0x52
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *AliveResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AliveResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Head != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Head.Size()))
		n19, err := m.Head.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n19
	}
	return i, nil
}

func (m *SimpleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimpleRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Head != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Head.Size()))
		n20, err := m.Head.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n20
	}
	if len(m.Title) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(len(m.Title)))
		i += copy(dAtA[i:], m.Title)
	}
	if len(m.Content) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(len(m.Content)))
		i += copy(dAtA[i:], m.Content)
	}
	if len(m.SampleJson) > 0 {
		for _, s := range m.SampleJson {
			dAtA[i] = 0x52
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *SimpleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimpleResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Head != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAlarmpb(dAtA, i, uint64(m.Head.Size()))
		n21, err := m.Head.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n21
	}
	return i, nil
}

func encodeVarintAlarmpb(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RequestHeader) Size() (n int) {
	var l int
	_ = l
	if m.ClusterId != 0 {
		n += 1 + sovAlarmpb(uint64(m.ClusterId))
	}
	return n
}

func (m *ResponseHeader) Size() (n int) {
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovAlarmpb(uint64(m.Code))
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	return n
}

func (m *SimpleAlarmRequest) Size() (n int) {
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	l = len(m.Describe)
	if l > 0 {
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	return n
}

func (m *SimpleAlarmResponse) Size() (n int) {
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	return n
}

func (m *TaskAlarmRequest) Size() (n int) {
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovAlarmpb(uint64(m.Type))
	}
	if m.Task != nil {
		l = m.Task.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.TaskTimeoutAlarm != nil {
		l = m.TaskTimeoutAlarm.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.TaskLongTimeRunningAlarm != nil {
		l = m.TaskLongTimeRunningAlarm.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	l = len(m.Describe)
	if l > 0 {
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if len(m.SampleJson) > 0 {
		for _, s := range m.SampleJson {
			l = len(s)
			n += 1 + l + sovAlarmpb(uint64(l))
		}
	}
	return n
}

func (m *TaskTimeout) Size() (n int) {
	var l int
	_ = l
	l = len(m.Start)
	if l > 0 {
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.Takes != 0 {
		n += 1 + sovAlarmpb(uint64(m.Takes))
	}
	return n
}

func (m *TaskLongTimeRunning) Size() (n int) {
	var l int
	_ = l
	l = len(m.Start)
	if l > 0 {
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.Takes != 0 {
		n += 1 + sovAlarmpb(uint64(m.Takes))
	}
	return n
}

func (m *TaskAlarmResponse) Size() (n int) {
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	return n
}

func (m *NodeRangeAlarmRequest) Size() (n int) {
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovAlarmpb(uint64(m.Type))
	}
	if m.RangeNoHbAlarm != nil {
		l = m.RangeNoHbAlarm.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.NodeNoHbAlarm != nil {
		l = m.NodeNoHbAlarm.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.NodeDiskSizeAlarm != nil {
		l = m.NodeDiskSizeAlarm.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.NodeLeaderCountAlarm != nil {
		l = m.NodeLeaderCountAlarm.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	l = len(m.Describe)
	if l > 0 {
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if len(m.SampleJson) > 0 {
		for _, s := range m.SampleJson {
			l = len(s)
			n += 1 + l + sovAlarmpb(uint64(l))
		}
	}
	return n
}

func (m *RangeNoHeartbeatAlarm) Size() (n int) {
	var l int
	_ = l
	if m.Range != nil {
		l = m.Range.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	l = len(m.LastHeartbeatTime)
	if l > 0 {
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	return n
}

func (m *NodeNoHeartbeatAlarm) Size() (n int) {
	var l int
	_ = l
	if m.Node != nil {
		l = m.Node.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	l = len(m.LastHeartbeatTime)
	if l > 0 {
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	return n
}

func (m *NodeDiskSizeAlarm) Size() (n int) {
	var l int
	_ = l
	if m.Node != nil {
		l = m.Node.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.DiskSize != 0 {
		n += 1 + sovAlarmpb(uint64(m.DiskSize))
	}
	return n
}

func (m *NodeLeaderCountAlarm) Size() (n int) {
	var l int
	_ = l
	if m.Node != nil {
		l = m.Node.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if m.LeaderCount != 0 {
		n += 1 + sovAlarmpb(uint64(m.LeaderCount))
	}
	return n
}

func (m *NodeRangeAlarmResponse) Size() (n int) {
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	return n
}

func (m *AliveRequest) Size() (n int) {
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if len(m.SampleJson) > 0 {
		for _, s := range m.SampleJson {
			l = len(s)
			n += 1 + l + sovAlarmpb(uint64(l))
		}
	}
	return n
}

func (m *AliveResponse) Size() (n int) {
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	return n
}

func (m *SimpleRequest) Size() (n int) {
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	if len(m.SampleJson) > 0 {
		for _, s := range m.SampleJson {
			l = len(s)
			n += 1 + l + sovAlarmpb(uint64(l))
		}
	}
	return n
}

func (m *SimpleResponse) Size() (n int) {
	var l int
	_ = l
	if m.Head != nil {
		l = m.Head.Size()
		n += 1 + l + sovAlarmpb(uint64(l))
	}
	return n
}

func sovAlarmpb(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozAlarmpb(x uint64) (n int) {
	return sovAlarmpb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RequestHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterId", wireType)
			}
			m.ClusterId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimpleAlarmRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimpleAlarmRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimpleAlarmRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &RequestHeader{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Describe", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Describe = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimpleAlarmResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimpleAlarmResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimpleAlarmResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &ResponseHeader{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskAlarmRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskAlarmRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskAlarmRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &RequestHeader{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (TaskAlarmType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Task", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Task == nil {
				m.Task = &taskpb.Task{}
			}
			if err := m.Task.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskTimeoutAlarm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TaskTimeoutAlarm == nil {
				m.TaskTimeoutAlarm = &TaskTimeout{}
			}
			if err := m.TaskTimeoutAlarm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskLongTimeRunningAlarm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TaskLongTimeRunningAlarm == nil {
				m.TaskLongTimeRunningAlarm = &TaskLongTimeRunning{}
			}
			if err := m.TaskLongTimeRunningAlarm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Describe", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Describe = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SampleJson = append(m.SampleJson, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskTimeout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskTimeout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskTimeout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Start = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Takes", wireType)
			}
			m.Takes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Takes |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskLongTimeRunning) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskLongTimeRunning: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskLongTimeRunning: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Start = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Takes", wireType)
			}
			m.Takes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Takes |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskAlarmResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskAlarmResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskAlarmResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &ResponseHeader{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeRangeAlarmRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeRangeAlarmRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeRangeAlarmRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &RequestHeader{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (NodeRangeAlarmType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RangeNoHbAlarm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RangeNoHbAlarm == nil {
				m.RangeNoHbAlarm = &RangeNoHeartbeatAlarm{}
			}
			if err := m.RangeNoHbAlarm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeNoHbAlarm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NodeNoHbAlarm == nil {
				m.NodeNoHbAlarm = &NodeNoHeartbeatAlarm{}
			}
			if err := m.NodeNoHbAlarm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeDiskSizeAlarm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NodeDiskSizeAlarm == nil {
				m.NodeDiskSizeAlarm = &NodeDiskSizeAlarm{}
			}
			if err := m.NodeDiskSizeAlarm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeLeaderCountAlarm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NodeLeaderCountAlarm == nil {
				m.NodeLeaderCountAlarm = &NodeLeaderCountAlarm{}
			}
			if err := m.NodeLeaderCountAlarm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Describe", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Describe = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SampleJson = append(m.SampleJson, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RangeNoHeartbeatAlarm) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RangeNoHeartbeatAlarm: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RangeNoHeartbeatAlarm: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Range", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Range == nil {
				m.Range = &metapb.Range{}
			}
			if err := m.Range.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastHeartbeatTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastHeartbeatTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeNoHeartbeatAlarm) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeNoHeartbeatAlarm: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeNoHeartbeatAlarm: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Node == nil {
				m.Node = &metapb.Node{}
			}
			if err := m.Node.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastHeartbeatTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastHeartbeatTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeDiskSizeAlarm) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeDiskSizeAlarm: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeDiskSizeAlarm: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Node == nil {
				m.Node = &metapb.Node{}
			}
			if err := m.Node.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiskSize", wireType)
			}
			m.DiskSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiskSize |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeLeaderCountAlarm) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeLeaderCountAlarm: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeLeaderCountAlarm: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Node == nil {
				m.Node = &metapb.Node{}
			}
			if err := m.Node.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderCount", wireType)
			}
			m.LeaderCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaderCount |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeRangeAlarmResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeRangeAlarmResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeRangeAlarmResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &ResponseHeader{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AliveRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AliveRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AliveRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &RequestHeader{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SampleJson = append(m.SampleJson, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AliveResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AliveResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AliveResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &ResponseHeader{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimpleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimpleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimpleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &RequestHeader{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SampleJson = append(m.SampleJson, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimpleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimpleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimpleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAlarmpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Head == nil {
				m.Head = &ResponseHeader{}
			}
			if err := m.Head.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlarmpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAlarmpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAlarmpb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAlarmpb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAlarmpb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthAlarmpb
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowAlarmpb
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipAlarmpb(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthAlarmpb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAlarmpb   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("alarmpb.proto", fileDescriptorAlarmpb) }

var fileDescriptorAlarmpb = []byte{
	// 899 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x96, 0xdd, 0x6e, 0x1a, 0x47,
	0x14, 0xc7, 0xbd, 0x06, 0xec, 0x70, 0xf8, 0x10, 0x8c, 0xb1, 0x8d, 0x48, 0x42, 0xdc, 0xed, 0x8d,
	0xe5, 0x4a, 0x44, 0x4a, 0xae, 0x5a, 0xb5, 0x52, 0x70, 0xa0, 0x36, 0x8d, 0xbb, 0x48, 0x03, 0xbe,
	0x69, 0x22, 0xad, 0x16, 0x18, 0xe1, 0x2d, 0xeb, 0x19, 0xba, 0x33, 0x54, 0x4a, 0x9e, 0xa1, 0x0f,
	0xd0, 0xab, 0x3e, 0x4f, 0x2f, 0xfb, 0x08, 0x95, 0x7b, 0xd1, 0x8b, 0xbe, 0x44, 0x35, 0x1f, 0x8b,
	0x77, 0x0c, 0x96, 0x63, 0xae, 0xe0, 0x9c, 0x39, 0xfc, 0xe6, 0xec, 0xfc, 0xff, 0x73, 0x58, 0x28,
	0x05, 0x51, 0x10, 0x5f, 0xcf, 0x47, 0xad, 0x79, 0xcc, 0x04, 0x43, 0xbb, 0x26, 0x6c, 0xd4, 0xa6,
	0x6c, 0xca, 0x54, 0xee, 0xa5, 0xfc, 0xa6, 0x97, 0x1b, 0x45, 0x11, 0xf0, 0x59, 0x52, 0xdc, 0x28,
	0x5e, 0x13, 0x11, 0x24, 0x91, 0xdb, 0x82, 0x12, 0x26, 0xbf, 0x2c, 0x08, 0x17, 0xe7, 0x24, 0x98,
	0x90, 0x18, 0x3d, 0x07, 0x18, 0x47, 0x0b, 0x2e, 0x48, 0xec, 0x87, 0x93, 0xba, 0x73, 0xe4, 0x1c,
	0x67, 0x70, 0xde, 0x64, 0x7a, 0x13, 0xf7, 0x1b, 0x28, 0x63, 0xc2, 0xe7, 0x8c, 0x72, 0x62, 0x7e,
	0x80, 0x20, 0x3b, 0x66, 0x13, 0xa2, 0x4a, 0x73, 0x58, 0x7d, 0x47, 0x35, 0xc8, 0x91, 0x38, 0x66,
	0x71, 0x7d, 0xfb, 0xc8, 0x39, 0xce, 0x63, 0x1d, 0xb8, 0x1f, 0x00, 0x0d, 0xc2, 0xeb, 0x79, 0x44,
	0xda, 0xb2, 0x5d, 0xb3, 0x2d, 0x3a, 0x81, 0xec, 0x15, 0x09, 0xf4, 0x56, 0x85, 0x57, 0x07, 0xad,
	0xe4, 0xd1, 0xac, 0xb6, 0xb0, 0xaa, 0x41, 0x0d, 0x78, 0xd2, 0x21, 0x7c, 0x1c, 0x87, 0x23, 0x62,
	0xd0, 0xcb, 0xd8, 0x3d, 0x85, 0x3d, 0x8b, 0xae, 0x9b, 0x44, 0x5f, 0x59, 0xf8, 0xc3, 0x14, 0x3e,
	0xfd, 0x14, 0x9a, 0xef, 0xfe, 0xb7, 0x0d, 0x95, 0x61, 0xc0, 0x67, 0x1b, 0x37, 0x78, 0x02, 0x59,
	0xf1, 0x71, 0xae, 0x9b, 0x2b, 0xa7, 0x6a, 0x97, 0xd0, 0xe1, 0xc7, 0x39, 0xc1, 0xaa, 0x06, 0x1d,
	0x41, 0x56, 0x0a, 0x53, 0xcf, 0x28, 0x6e, 0xb1, 0x65, 0x54, 0x92, 0xa5, 0x58, 0xad, 0xa0, 0x53,
	0x40, 0xf2, 0xd3, 0x17, 0xe1, 0x35, 0x61, 0x0b, 0xe1, 0x2b, 0x5a, 0x3d, 0xab, 0xea, 0x6b, 0x16,
	0x7b, 0xa8, 0x2b, 0x70, 0x45, 0xdc, 0x06, 0x6a, 0x3f, 0xf4, 0x01, 0x9e, 0x29, 0x46, 0xc4, 0xe8,
	0x54, 0x81, 0xfc, 0x78, 0x41, 0x69, 0x48, 0xa7, 0x86, 0x96, 0x53, 0xb4, 0x67, 0x16, 0xed, 0x82,
	0xd1, 0xa9, 0x84, 0x60, 0x5d, 0x89, 0xeb, 0x62, 0x35, 0xa9, 0xe9, 0x69, 0x41, 0x76, 0x6c, 0x41,
	0xd0, 0x0b, 0x28, 0xf0, 0x40, 0x0a, 0xe2, 0xff, 0xcc, 0x19, 0xad, 0xc3, 0x51, 0xe6, 0x38, 0x8f,
	0x41, 0xa7, 0x7e, 0xe0, 0x8c, 0xba, 0x5f, 0x43, 0x21, 0xd5, 0xbb, 0x34, 0x0d, 0x17, 0x41, 0x2c,
	0x12, 0xd3, 0xa8, 0x40, 0x66, 0x45, 0x30, 0x23, 0x5c, 0x1d, 0x53, 0x06, 0xeb, 0xc0, 0x6d, 0xc3,
	0xde, 0x9a, 0x46, 0x1f, 0x85, 0x78, 0x03, 0xd5, 0x94, 0xd4, 0x9b, 0xb8, 0xe5, 0xdf, 0x0c, 0xec,
	0x7b, 0x6c, 0x42, 0x70, 0x40, 0xa7, 0x9b, 0x7b, 0xfa, 0xa5, 0x65, 0x99, 0xa7, 0xcb, 0x5a, 0x9b,
	0x9c, 0xf2, 0x4d, 0x0f, 0xaa, 0xb1, 0xcc, 0xfb, 0x94, 0xf9, 0x57, 0x23, 0x23, 0xa3, 0x36, 0x51,
	0xf3, 0x76, 0x27, 0x59, 0xe1, 0xb1, 0x73, 0x12, 0xc4, 0x62, 0x44, 0x02, 0x6d, 0x06, 0x5c, 0x8e,
	0x4d, 0x7a, 0xa4, 0xe5, 0xfb, 0x1e, 0x2a, 0x94, 0x4d, 0x6c, 0x92, 0xb6, 0xd7, 0x73, 0xab, 0x8f,
	0x15, 0x50, 0x89, 0xea, 0xac, 0xe1, 0xbc, 0x83, 0x9a, 0xe2, 0x4c, 0x42, 0x3e, 0xf3, 0x79, 0xf8,
	0x89, 0x58, 0xe6, 0x6a, 0x58, 0xac, 0x4e, 0xc8, 0x67, 0x83, 0xf0, 0x93, 0x39, 0xb0, 0x2a, 0xbd,
	0x9b, 0x42, 0x43, 0x38, 0x54, 0xb0, 0x48, 0x9d, 0x92, 0x3f, 0x66, 0x0b, 0x9a, 0x58, 0x7f, 0x67,
	0x4d, 0x6f, 0x17, 0xaa, 0xec, 0xad, 0xac, 0xd2, 0x48, 0xd5, 0xca, 0xdd, 0xac, 0xe5, 0xd4, 0xdd,
	0xc7, 0x3a, 0x35, 0x82, 0xfd, 0xb5, 0x07, 0x8a, 0xbe, 0x84, 0x9c, 0x3a, 0x52, 0xa3, 0x74, 0xa9,
	0x65, 0x86, 0xab, 0xaa, 0xc6, 0x7a, 0x0d, 0xb5, 0x60, 0x2f, 0x0a, 0xb8, 0xf0, 0xaf, 0x92, 0xdf,
	0xaa, 0x7b, 0x68, 0x3c, 0x5a, 0x95, 0x4b, 0x4b, 0xaa, 0x34, 0xb3, 0x7b, 0x05, 0xb5, 0x75, 0x87,
	0x2e, 0x07, 0x06, 0x4d, 0x26, 0xad, 0x1c, 0x18, 0x66, 0x2f, 0x65, 0x14, 0xb5, 0xf2, 0xe8, 0x9d,
	0x30, 0x54, 0x57, 0x24, 0xf9, 0x8c, 0x6d, 0x9e, 0x42, 0x7e, 0xa9, 0xb4, 0x82, 0x67, 0xf0, 0x93,
	0x89, 0x61, 0xb8, 0xef, 0x75, 0xf7, 0x2b, 0x02, 0x3c, 0x8c, 0xfd, 0x02, 0x8a, 0x69, 0xcd, 0x0d,
	0xb9, 0x10, 0xdd, 0x92, 0xdc, 0x2e, 0x1c, 0xdc, 0xbd, 0x71, 0x9b, 0xdc, 0xdc, 0xf7, 0x50, 0x6c,
	0x47, 0xe1, 0xaf, 0x64, 0x93, 0xfb, 0xfa, 0xa0, 0x59, 0xbe, 0x85, 0x92, 0x81, 0x6f, 0xd2, 0xda,
	0x6f, 0x0e, 0x94, 0xf4, 0xff, 0xd8, 0x26, 0xcd, 0xc9, 0x51, 0x17, 0x8a, 0x28, 0x91, 0x5c, 0x07,
	0xa8, 0x0e, 0xbb, 0x63, 0x46, 0x05, 0xa1, 0x42, 0xcd, 0x89, 0x3c, 0x4e, 0xc2, 0x87, 0x1f, 0xe6,
	0x3b, 0x28, 0x27, 0xdd, 0x6c, 0xf0, 0x34, 0x27, 0xaf, 0xa1, 0x64, 0xfd, 0xf5, 0xa1, 0x02, 0xec,
	0x0e, 0x7b, 0x3f, 0x76, 0xfb, 0x97, 0xc3, 0xca, 0x16, 0xda, 0x87, 0xea, 0x45, 0xdf, 0x3b, 0xf3,
	0x65, 0xc6, 0xc7, 0x97, 0x9e, 0xd7, 0xf3, 0xce, 0x2a, 0xce, 0x09, 0x05, 0xb4, 0x3a, 0xfc, 0xd0,
	0x01, 0x20, 0xdc, 0xf6, 0xce, 0xba, 0xbe, 0xd7, 0xf7, 0xcf, 0xbb, 0x6d, 0x3c, 0x3c, 0xed, 0xb6,
	0x0d, 0xc4, 0xeb, 0x77, 0xee, 0xa4, 0x1d, 0x84, 0xa0, 0xac, 0xd2, 0x9d, 0xde, 0xe0, 0x9d, 0x3f,
	0xe8, 0xfd, 0xd4, 0xad, 0x6c, 0x2f, 0x4b, 0x2f, 0xba, 0xed, 0x4e, 0x17, 0xfb, 0x6f, 0xfb, 0x97,
	0xde, 0xb0, 0x92, 0x79, 0xf5, 0x87, 0x03, 0x39, 0xed, 0xd1, 0x01, 0x94, 0xed, 0x9d, 0x51, 0xf3,
	0x9e, 0x79, 0x6c, 0x0e, 0xbf, 0xf1, 0xe2, 0xde, 0x75, 0x7d, 0x1a, 0xee, 0x16, 0x7a, 0x03, 0x85,
	0xd4, 0x8b, 0x09, 0xba, 0x15, 0xd0, 0x92, 0xb9, 0x71, 0xb8, 0x92, 0x4f, 0x08, 0xa7, 0x95, 0x3f,
	0x6f, 0x9a, 0xce, 0x5f, 0x37, 0x4d, 0xe7, 0xef, 0x9b, 0xa6, 0xf3, 0xfb, 0x3f, 0xcd, 0xad, 0xd1,
	0x8e, 0x7a, 0x7b, 0x7b, 0xfd, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x5b, 0x88, 0x44, 0x09,
	0x0a, 0x00, 0x00,
}
